server:
  port: 8054

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        - id: authentication
          uri: lb://authentication
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authentication
                fallbackuri: forward:/authServiceFallback
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userServiceFallback
        - id: report
          uri: lb://report
          predicates:
            - Path=/report/**
          filters:
            - name: CircuitBreaker
              args:
                name: report
                fallbackuri: forward:/reportServiceFallback
        - id: adding-questions
          uri: lb://adding-questions
          predicates:
            - Path=/add/**
          filters:
            - name: CircuitBreaker
              args:
                name: adding-questions
                fallbackuri: forward:/addQuestionServiceFallback
        - id: schedule-exam
          uri: lb://schedule-exam
          predicates:
            - Path=/schedule/**
          filters:
            - name: CircuitBreaker
              args:
                name: schedule-exam
                fallbackuri: forward:/examServiceFallback



hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream